version: 2
workflows:
  version: 2
  test:
    jobs:
      - unit_test:
          filters:
            tags:
              only: /.*/
      - checks:
          filters:
            tags:
              only: /.*/
      - dev_api_test:
          filters:
            tags:
              only: /.*/
      - dev_api_checks:
          filters:
            tags:
              only: /.*/
      - build-and-release:
          requires: [unit_test, checks, dev_api_test, dev_api_checks]
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
jobs:
  unit_test:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
      - image: kennethreitz/httpbin
        name: httpbin
    steps:
      - checkout
      - run:
          name: Set folder
          command: mv source old; mv old/* ./; rm -rf old;
      - run:
          name: composer install
          command: composer install
      - run:
          name: Tests
          command: composer tests

  checks:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
    steps:
      - checkout
      - run:
          name: Copy files
          command: mv source old; mv old/* ./; rm -rf old;
      - run:
          name: Copy dependencies
          command: cp /home/circleci/vendor/ ./vendor/ -R
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Run Lint
          command: composer lint

  dev_api_test:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
    steps:
      - checkout
      - run:
          name: Set folder
          command: mv api_dev old; mv old/* ./; rm -rf old;
      - run:
          name: composer install
          command: composer install
      - run:
          name: Tests
          command: composer tests

  dev_api_checks:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
    steps:
      - checkout
      - run:
          name: Copy files
          command: mv api_dev old; mv old/* ./; rm -rf old;
      - run:
          name: Copy dependencies
          command: cp /home/circleci/vendor/ ./vendor/ -R
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Run Lint
          command: composer lint

  dev_api_test:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
    steps:
      - checkout
      - run:
          name: Set folder
          command: mv api_dev old; mv old/* ./; rm -rf old;
      - run:
          name: composer install
          command: composer install
      - run:
          name: Tests
          command: composer tests

  dev_api_checks:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
    steps:
      - checkout
      - run:
          name: Copy files
          command: mv api_dev old; mv old/* ./; rm -rf old;
      - run:
          name: Copy dependencies
          command: cp /home/circleci/vendor/ ./vendor/ -R
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Run Lint
          command: composer lint

  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: TO BE IMPLEMENTED
          command: echo "Deploy here"
