version: 2
workflows:
  version: 2
  test:
    jobs:
      - unit_test:
          filters:
            tags:
              only: /.*/
      - checks:
          filters:
            tags:
              only: /.*/
      - dev_api_test:
          filters:
            tags:
              only: /.*/
      - dev_api_checks:
          filters:
            tags:
              only: /.*/
      - dev_frontend_test:
          filters:
            tags:
              only: /.*/
      - dev_frontend_checks:
          filters:
            tags:
              only: /.*/
      - build-and-release:
          filters:
            tags:
              only: /.*/
      - update-description:
          requires: [build-and-release]
          filters:
            tags:
              only: /.*/
jobs:
  unit_test:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
      - image: kennethreitz/httpbin
        name: httpbin
    steps:
      - checkout
      - run:
          name: Remove other folders
          command: rm -rf dev
      - run:
          name: Set folder
          command: mv source old; mv old/* ./; rm -rf old;
      - run:
          name: Copy dependencies
          command: cp /home/circleci/vendor/ ./vendor/ -R
      - run:
          name: composer install
          command: composer install
      - run:
          name: Tests
          command: composer tests

  checks:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
    steps:
      - checkout
      - run:
          name: Remove other folders
          command: rm -rf dev
      - run:
          name: Copy files
          command: mv source old; mv old/* ./; rm -rf old;
      - run:
          name: Copy dependencies
          command: cp /home/circleci/vendor/ ./vendor/ -R
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Run Lint
          command: composer lint

  dev_api_test:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
        environment:
          API_DEV_MYSQL_HOST: mysql
          API_DEV_MYSQL_PORT: 3306
          API_DEV_MYSQL_USER: tent
          API_DEV_MYSQL_PASSWORD: tent
          API_DEV_MYSQL_TEST_DATABASE: tent
      - image: cimg/mysql:8.0
        name: mysql
        environment:
          MYSQL_DATABASE: tent
          MYSQL_USER: tent
          MYSQL_PASSWORD: tent
          MYSQL_ROOT_PASSWORD: tent
    steps:
      - checkout
      - run:
          name: Remove other folders
          command: rm -rf source
      - run:
          name: Set folder
          command: mv dev/api/* ./; rm -rf dev;
      - run:
          name: Copy dependencies
          command: cp /home/circleci/vendor/ ./vendor/ -R
      - run:
          name: composer install
          command: composer install
      - run:
          name: Wait for DB
          command: php ./bin/wait_for_database.php
      - run:
          name: Ensure database exists
          command: php ./bin/create_databases.php
      - run:
          name: EnsurMigrate database
          command: php ./bin/migrate_databases.php
      - run:
          name: Tests
          command: composer tests

  dev_api_checks:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
    steps:
      - checkout
      - run:
          name: Remove other folders
          command: rm -rf source
      - run:
          name: Set folder
          command: mv dev/api/* ./; rm -rf dev;
      - run:
          name: Copy dependencies
          command: cp /home/circleci/vendor/ ./vendor/ -R
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Run Lint
          command: composer lint

  dev_frontend_test:
    docker:
      - image: darthjee/circleci_node:0.2.1
    steps:
      - checkout
      - run:
          name: Remove other folders
          command: rm -rf source
      - run:
          name: Set folder
          command: mv dev/frontend/* ./; rm -rf dev;
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Tests
          command: npm test

  dev_frontend_checks:
    docker:
      - image: darthjee/circleci_node:0.2.1
    steps:
      - checkout
      - run:
          name: Remove other folders
          command: rm -rf source
      - run:
          name: Set folder
          command: mv dev/frontend/* ./; rm -rf dev;
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Check JS Lint
          command: npm run lint

  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker build --platform linux/amd64 -f dockerfiles/Dockerfile.tent . -t darthjee/tent:latest -t darthjee/tent:0.0.1
      - run:
          name: Docker login
          command: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - run:
          name: Docker push
          command: docker push darthjee/tent:0.0.1
      - run:
          name: Docker release
          command: docker push darthjee/tent:latest
  update-description:
    docker:
      - image: darthjee/scripts:0.6.0
    steps:
      - checkout
      - run:
          name: Docker push description
          command: source /home/scripts/sbin/docker_hub.sh login; /bin/sh /home/scripts/sbin/docker_hub.sh push_description darthjee/tent README.md
