version: 2
workflows:
  version: 2
  test:
    jobs:
      - unit_test:
          filters:
            tags:
              only: /.*/
      - checks:
          filters:
            tags:
              only: /.*/
      - dev_api_test:
          filters:
            tags:
              only: /.*/
      - dev_api_checks:
          filters:
            tags:
              only: /.*/
      - build-and-release:
          requires: [unit_test, checks, dev_api_test, dev_api_checks]
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
jobs:
  unit_test:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
      - image: kennethreitz/httpbin
        name: httpbin
    steps:
      - checkout
      - run:
          name: Remove other folders
          command: rm -rf api_dev
      - run:
          name: Set folder
          command: mv source old; mv old/* ./; rm -rf old;
      - run:
          name: composer install
          command: composer install
      - run:
          name: Tests
          command: composer tests

  checks:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
    steps:
      - checkout
      - run:
          name: Remove other folders
          command: rm -rf api_dev
      - run:
          name: Copy files
          command: mv source old; mv old/* ./; rm -rf old;
      - run:
          name: Copy dependencies
          command: cp /home/circleci/vendor/ ./vendor/ -R
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Run Lint
          command: composer lint

  dev_api_test:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
        environment:
          API_DEV_MYSQL_HOST: mysql
          API_DEV_MYSQL_PORT: 3306
          API_DEV_MYSQL_USER: tent
          API_DEV_MYSQL_PASSWORD: tent
          API_DEV_MYSQL_TEST_DATABASE: tent
      - image: cimg/mysql:8.0
        name: mysql
        environment:
          MYSQL_DATABASE: tent
          MYSQL_USER: tent
          MYSQL_PASSWORD: tent
          MYSQL_ROOT_PASSWORD: tent
    steps:
      - checkout
      - run:
          name: Remove other folders
          command: rm -rf source
      - run:
          name: Set folder
          command: mv api_dev/* ./; rm -rf api_dev;
      - run:
          name: composer install
          command: composer install
      - run:
          name: Tests
          command: sleep 5; composer tests

  dev_api_checks:
    docker:
      - image: darthjee/circleci_tent-base:0.0.1
    steps:
      - checkout
      - run:
          name: Remove other folders
          command: rm -rf source
      - run:
          name: Set folder
          command: mv api_dev/* ./; rm -rf api_dev;
      - run:
          name: Copy dependencies
          command: cp /home/circleci/vendor/ ./vendor/ -R
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Run Lint
          command: composer lint

  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: TO BE IMPLEMENTED
          command: echo "Deploy here"
